#!/usr/bin/env python3
"""Build equal-weight Python composite-factor candidates without calling PandaAI.

The input manifest is ``name ~ Python file ~ direction``.  Given N independently
authored component factors, this writes every N-choose-K composite as one Python
``Factor`` class.  A component marked direction 0 is sign-flipped, then every
component is cross-sectionally Z-scored before equal-weighting.

For example, six components with ``--choose 5`` generate six composites.  The
generated candidates are useful for an *online composite-signal proxy*: PandaAI
backtests the combined ranking as one factor.  They do not create a competition
factor pool and do not replace its five separately valid factors.
"""

from __future__ import annotations

import argparse
import ast
import hashlib
import itertools
import json
import re
import sys
from dataclasses import dataclass
from pathlib import Path


@dataclass(frozen=True)
class Component:
    name: str
    path: Path
    direction: int
    body: list[str]
    digest: str


def identifier(name: str) -> str:
    """Create a stable Python identifier without exposing a research name in output code."""
    return "component_" + hashlib.sha256(name.encode("utf-8")).hexdigest()[:10]


def method_body(source: str, path: Path) -> list[str]:
    """Extract the body of the sole Factor.calculate method, preserving source lines."""
    try:
        tree = ast.parse(source, filename=str(path))
    except SyntaxError as exc:
        raise ValueError(f"invalid Python: {exc}") from exc
    classes = [node for node in tree.body if isinstance(node, ast.ClassDef)
               and any(isinstance(base, ast.Name) and base.id == "Factor" for base in node.bases)]
    if len(classes) != 1:
        raise ValueError("must contain exactly one class directly inheriting Factor")
    methods = [node for node in classes[0].body if isinstance(node, ast.FunctionDef)
               and node.name == "calculate"]
    if len(methods) != 1 or len(methods[0].args.args) < 2:
        raise ValueError("Factor class must define calculate(self, factors)")
    method = methods[0]
    if not method.body:
        raise ValueError("calculate method is empty")
    lines = source.splitlines()
    start, end = method.body[0].lineno - 1, method.end_lineno
    body = lines[start:end]
    # Method statements are indented by one level in their original class.  The generated helper
    # needs the same body under its own method, so remove exactly that common indentation.
    nonblank = [line for line in body if line.strip()]
    indent = min(len(line) - len(line.lstrip()) for line in nonblank)
    return [line[indent:] if line.strip() else "" for line in body]


def read_manifest(path: Path) -> list[Component]:
    components: list[Component] = []
    names: set[str] = set()
    for line_no, raw in enumerate(path.read_text(encoding="utf-8").splitlines(), 1):
        line = raw.strip()
        if not line or line.startswith("#"):
            continue
        parts = [part.strip() for part in line.split("~")]
        if len(parts) != 3:
            raise ValueError(f"{path}:{line_no}: expected name ~ Python file ~ direction")
        name, relative, direction_text = parts
        if not name or name in names:
            raise ValueError(f"{path}:{line_no}: component names must be non-empty and unique")
        if direction_text not in {"0", "1"}:
            raise ValueError(f"{path}:{line_no}: direction must be 0 or 1")
        factor_path = (path.parent / relative).resolve()
        if factor_path.suffix.lower() != ".py":
            raise ValueError(f"{path}:{line_no}: component must be a .py file")
        try:
            source = factor_path.read_text(encoding="utf-8")
        except OSError as exc:
            raise ValueError(f"{path}:{line_no}: cannot read {factor_path}: {exc}") from exc
        components.append(Component(
            name=name,
            path=factor_path,
            direction=int(direction_text),
            body=method_body(source, factor_path),
            digest=hashlib.sha256(source.encode("utf-8")).hexdigest(),
        ))
        names.add(name)
    return components


def render_factor(parts: tuple[Component, ...], class_name: str) -> str:
    lines = [
        "# Generated by scripts/build_composites.py. Do not hand-edit: regenerate from the manifest.",
        "# Online composite-signal proxy only; this file represents one factor, not a formal factor pool.",
        "",
        f"class {class_name}(Factor):",
    ]
    for component in parts:
        lines.extend(["", f"    def _{identifier(component.name)}(self, factors):"])
        lines.extend(f"        {line}" if line else "" for line in component.body)
    lines.extend(["", "    def calculate(self, factors):"])
    normalized = []
    for index, component in enumerate(parts, 1):
        call = f"self._{identifier(component.name)}(factors)"
        aligned = call if component.direction == 1 else f"-({call})"
        var = f"signal_{index}"
        lines.append(f"        {var} = ZSCORE({aligned})")
        normalized.append(var)
    lines.append(f"        return ({' + '.join(normalized)}) / {len(parts)}")
    return "\n".join(lines) + "\n"


def safe_prefix(prefix: str) -> str:
    value = re.sub(r"[^A-Za-z0-9_-]+", "-", prefix).strip("-")
    if not value:
        raise ValueError("--prefix needs at least one ASCII letter or digit")
    return value


def main() -> int:
    parser = argparse.ArgumentParser(description=__doc__.splitlines()[0])
    parser.add_argument("manifest", type=Path, help="name ~ Python file ~ direction")
    parser.add_argument("--choose", type=int, default=5, help="components per composite (default: 5)")
    parser.add_argument("--out-dir", type=Path, required=True, help="generated files and registry directory")
    parser.add_argument("--prefix", default="C-PROBE", help="opaque output candidate prefix")
    args = parser.parse_args()

    try:
        components = read_manifest(args.manifest)
        prefix = safe_prefix(args.prefix)
        if not 1 <= args.choose <= len(components):
            raise ValueError(f"--choose must be between 1 and {len(components)}")
    except ValueError as exc:
        print(f"error: {exc}", file=sys.stderr)
        return 2

    args.out_dir.mkdir(parents=True, exist_ok=True)
    candidates, registry = [], []
    for index, group in enumerate(itertools.combinations(components, args.choose), 1):
        candidate_name = f"{prefix}-{index:02d}"
        filename = f"{candidate_name}.py"
        output = args.out_dir / filename
        output.write_text(render_factor(group, f"Composite{index:02d}"), encoding="utf-8")
        candidates.append(f"{candidate_name} ~ {filename} ~ 1")
        selected = {component.name for component in group}
        registry.append({
            "candidate": candidate_name,
            "file": filename,
            "components": [
                {"name": component.name, "path": str(component.path), "direction": component.direction,
                 "sha256": component.digest}
                for component in group
            ],
            "excluded": [component.name for component in components if component.name not in selected],
            "meaning": "online composite-signal proxy, not an official factor pool",
        })
    (args.out_dir / "composites.txt").write_text("\n".join(candidates) + "\n", encoding="utf-8")
    (args.out_dir / "registry.json").write_text(
        json.dumps({"choose": args.choose, "component_count": len(components), "candidates": registry},
                   ensure_ascii=False, indent=2) + "\n", encoding="utf-8")
    print(f"generated {len(candidates)} composite factor file(s) in {args.out_dir}")
    print(f"run manifest: {args.out_dir / 'composites.txt'}")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
